package repository

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/mmirolim/vibecodemap/internal/scoping"
)

func TestScanAppliesDefaultsRuleFileMarkersAndBudgets(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "main.go", "package main\n")
	writeTestFile(t, root, "node_modules/pkg/index.js", "export {}\n")
	writeTestFile(t, root, "lib/model.freezed.dart", "class Model {}\n")
	writeTestFile(t, root, "generated.go", "// Code generated by fixture; DO NOT EDIT.\npackage fixture\n")
	writeTestFile(t, root, "fixtures/data.json", "{}\n")
	writeTestFile(t, root, "fixtures/owned.go", "package owned\n")
	writeTestFile(t, root, "large.bin", "12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901")
	writeTestFile(t, root, ".vcmignore", "summarize fixtures/**\n!fixtures/owned.go\n")

	options := DefaultOptions()
	options.ReadGitignore = false
	options.MaxFileBytes = 100
	report, err := Scan(context.Background(), root, options)
	if err != nil {
		t.Fatal(err)
	}

	assertEntry(t, report, "main.go", scoping.Analyze, "")
	assertEntry(t, report, "node_modules", scoping.Ignore, "deps.node-modules")
	assertEntry(t, report, "lib/model.freezed.dart", scoping.Summarize, "generated.dart")
	assertEntry(t, report, "generated.go", scoping.Summarize, "generated.go-header")
	assertEntry(t, report, "fixtures/data.json", scoping.Summarize, "vcmignore.1")
	assertEntry(t, report, "fixtures/owned.go", scoping.Analyze, "vcmignore.2")
	assertEntry(t, report, "large.bin", scoping.Summarize, "budget.max-file-bytes")
}

func TestScanUsesGitForGitignoreSemantics(t *testing.T) {
	git, err := exec.LookPath("git")
	if err != nil {
		t.Skip("git is unavailable")
	}
	root := t.TempDir()
	if output, err := exec.Command(git, "-C", root, "init", "--quiet").CombinedOutput(); err != nil {
		t.Fatalf("git init: %v: %s", err, output)
	}
	writeTestFile(t, root, ".gitignore", "*.scratch\nignored-tree/\n")
	writeTestFile(t, root, "notes.scratch", "discard\n")
	writeTestFile(t, root, "ignored-tree/deep/file.txt", "discard without walking the tree\n")
	writeTestFile(t, root, "main.go", "package main\n")

	options := DefaultOptions()
	report, err := Scan(context.Background(), root, options)
	if err != nil {
		t.Fatal(err)
	}
	if !report.GitignoreApplied {
		t.Fatalf("expected gitignore to be applied: %+v", report.Warnings)
	}
	assertEntry(t, report, "notes.scratch", scoping.Ignore, "gitignore")
	assertEntry(t, report, "ignored-tree", scoping.Ignore, "gitignore")
	if total := report.Totals[scoping.Ignore]; total.PrunedDirectories == 0 {
		t.Fatalf("expected pruned directory audit count: %+v", total)
	}
	for _, entry := range report.Entries {
		if entry.Path == "ignored-tree/deep/file.txt" {
			t.Fatalf("ignored directory was not pruned: %+v", entry)
		}
	}
	assertEntry(t, report, "main.go", scoping.Analyze, "")
}

func writeTestFile(t *testing.T, root, relative, contents string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(relative))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(contents), 0o600); err != nil {
		t.Fatal(err)
	}
}

func assertEntry(t *testing.T, report Report, path string, action scoping.Action, rule string) {
	t.Helper()
	for _, entry := range report.Entries {
		if entry.Path != path {
			continue
		}
		if entry.Action != action || entry.RuleID != rule {
			t.Fatalf("%s = (%s, %s), want (%s, %s): %+v", path, entry.Action, entry.RuleID, action, rule, entry)
		}
		return
	}
	t.Fatalf("missing inventory entry %q: %+v", path, report.Entries)
}
