package scoping

import (
	"os"
	"path/filepath"
	"testing"
)

func TestDefaultPolicy(t *testing.T) {
	policy, err := DefaultPolicy()
	if err != nil {
		t.Fatal(err)
	}

	tests := []struct {
		path   string
		prefix string
		action Action
		rule   string
	}{
		{"app/service.py", "from pathlib import Path\n", Analyze, ""},
		{"frontend/node_modules/react/index.js", "", Ignore, "deps.node-modules"},
		{".venv/lib/python3.13/site-packages/x.py", "", Ignore, "deps.python-venv"},
		{"local/lib/python3.13/site-packages/x.py", "", Ignore, "deps.python-site-packages"},
		{"api/vendor/example.com/mod/x.go", "", Ignore, "deps.go-vendor"},
		{"api/user.pb.go", "", Summarize, "generated.go-protobuf"},
		{"api/stringer.go", "// Code generated by stringer; DO NOT EDIT.\n", Summarize, "generated.go-header"},
		{"web/client.generated.ts", "", Summarize, "generated.javascript"},
		{"mobile/.dart_tool/package_config.json", "", Ignore, "cache.dart"},
		{"ios/.symlinks/plugins/x/file.swift", "", Ignore, "build.flutter-ios-symlinks"},
		{"ios/DerivedData/App/Build/app", "", Ignore, "cache.xcode"},
		{"android/.gradle/8.10/fileHashes.bin", "", Ignore, "cache.gradle"},
		{"lib/model.freezed.dart", "", Summarize, "generated.dart"},
		{"Sources/API/service.pb.swift", "", Summarize, "generated.swift"},
		{"bin/tool", "\x7fELF\x00binary", Summarize, "content.binary"},
		{"assets/.DS_Store", "\x00", Ignore, "os.metadata"},
	}

	for _, test := range tests {
		t.Run(test.path, func(t *testing.T) {
			decision := policy.Evaluate(test.path, []byte(test.prefix))
			if decision.Action != test.action {
				t.Fatalf("action = %q, want %q (%+v)", decision.Action, test.action, decision)
			}
			if decision.RuleID != test.rule {
				t.Fatalf("rule = %q, want %q (%+v)", decision.RuleID, test.rule, decision)
			}
		})
	}
}

func TestParseRuleFileAndOverride(t *testing.T) {
	directory := t.TempDir()
	path := filepath.Join(directory, ".vcmignore")
	contents := "# repository decisions\nignore fixtures/**\nsummarize snapshots/**\n!fixtures/owned.go\n"
	if err := os.WriteFile(path, []byte(contents), 0o600); err != nil {
		t.Fatal(err)
	}

	rules, err := ParseRuleFile(path)
	if err != nil {
		t.Fatal(err)
	}
	policy, err := NewDefaultPolicy(rules, nil)
	if err != nil {
		t.Fatal(err)
	}

	tests := []struct {
		path   string
		action Action
	}{
		{"fixtures/generated.go", Ignore},
		{"fixtures/owned.go", Analyze},
		{"snapshots/scene.json", Summarize},
	}
	for _, test := range tests {
		if decision := policy.Evaluate(test.path, nil); decision.Action != test.action {
			t.Fatalf("%s: action = %q, want %q (%+v)", test.path, decision.Action, test.action, decision)
		}
	}
}

func TestProjectRuleOverridesDefault(t *testing.T) {
	policy, err := NewPolicy(Analyze, []Rule{
		{ID: "default-generated", Pattern: "**/*.generated.ts", Action: Summarize, Priority: 50},
		{ID: "project-include-client", Pattern: "web/client.generated.ts", Action: Analyze, Priority: 100},
	}, nil)
	if err != nil {
		t.Fatal(err)
	}

	decision := policy.Evaluate("web/client.generated.ts", nil)
	if decision.Action != Analyze || decision.RuleID != "project-include-client" {
		t.Fatalf("unexpected decision: %+v", decision)
	}
}

func TestLaterRuleWinsPriorityTie(t *testing.T) {
	policy, err := NewPolicy(Analyze, []Rule{
		{ID: "first", Pattern: "**/*.go", Action: Summarize, Priority: 10},
		{ID: "second", Pattern: "cmd/**/*.go", Action: Analyze, Priority: 10},
	}, nil)
	if err != nil {
		t.Fatal(err)
	}

	decision := policy.Evaluate("cmd/vcm/main.go", nil)
	if decision.RuleID != "second" || decision.Action != Analyze {
		t.Fatalf("unexpected decision: %+v", decision)
	}
}

func TestInvalidGlob(t *testing.T) {
	_, err := NewPolicy(Analyze, []Rule{{ID: "bad", Pattern: "**/{one}", Action: Ignore}}, nil)
	if err == nil {
		t.Fatal("expected invalid brace group error")
	}
}
